### ISSUE TITLE
動画一覧ページに検索機能をつける

### ISSUE THREAD

**Issue by Yumikot** [Yumikot/poletricks#2]
##検索窓を作る

- gemを入れるranzack or searchcorp??

テストユーザーフィードバック

- 検索という単語から、虫めがねや検索窓を探してしまいました。

- 出来ればマスターチェック入れるページはもーちょいスクロール少なくても技数が見れるようにした方がいい

**Comment by Yumikot** [comment]
gemをranzakではなくSearchCopというやつのほうがもしかして良いのでは？？
[https://qiita.com/EastResident/items/092495a4eff8406bd492](url)

**Comment by Yumikot** [comment]
ransackを入れてエラーが消えましたが、
これってもしかして、動画一覧ページ自体が一枚ものだから、そのページに検索したものだけ表示されるってわけではないのでしょうか、、、？？
index.htm.erb
```
<%= search_form_for @q do |f| %>

  <%= f.label :title_cont %>
  <%= f.search_field :title_cont %>
　<%= f.submit %>
  
  <% end %>
```
trick.controller
```
def index
    @tricks = Trick.all
    @q = Trick.ransack(params[:q])
    @trick = @q.result(distinct: true)
  end
```
![スクリーンショット 2019-03-29 19 09 38](https://user-images.githubusercontent.com/22333359/55225562-42a0a480-5256-11e9-9665-91e4863e587c.png)

**Comment by happa** [comment]
むむ？ちょっと質問の意味がわからないですかね。どこに問題があるのかわからないです。これは検索して、それが言葉が含まれる動画一覧を表示していると思うのですが。

**Comment by Yumikot** [comment]
その言葉が含まれるということは"Phenix"で検索した場合
test
が出てくるのはおかしいのかな、機能してないのかな、と思い。
動画一覧上にはphenixというカードはあるのですが。

**Comment by Yumikot** [comment]
@happa 
ransackの公式のgithub見ながらコードは書いたのですが、
[https://github.com/activerecord-hackery/ransack](url)
自分の意図しているように実装ができないなあ:考え中:
という感じなんです。
わたしがしたいことは
スマホで検索する（trick名を含む、ex:handstand　という技を検索したいとして例えば、まんまhandstand
と検索バーに打ち込んでsearchボタンをおす）→表示画面（index.html.erb）の最上位にhandstandと名前が含まれたものが表示される（その他のものは表示されない）

現状：検索する→表示画面変わらず
コンソールを見てみると
```
Parameters: {"utf8"=>"✓", "q"=>{"title_cont"=>"Handstand"}, "commit"=>"Search"}
  Rendering tricks/index.html.erb within layouts/application
```
となっているので探しに行って、動画一覧ページにレンダリングされているんですが
その欲しかったトリックだけを抽出するということができない。
